apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-grafana-configmap
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
    - job_name: 'prometheus'
      static_configs:
      - targets: ['localhost:9090']
    - job_name: 'Prometheus-Actual'
      static_configs:
      - targets: ['129.154.40.209:30400']    
  datasource.yml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://129.154.40.209:30400